version: 0.1

environment_variables:
  plaintext:

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
  
  pre_build:
    commands:
      - echo env dump 
      - env
      - which mvn 
      
  
  build:
    commands:
      - mvn install
  
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - appspec.yml
    - target/SampleMavenTomcatApp.war
    - scripts/*
